//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Reservation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Image_Detail
    {
        [Key]
        [StringLength(50)]
        public string imageId { get; set; }

        [Required]
        [StringLength(50)]
        public string typeId { get; set; }

        [Required]
        [StringLength(50)]
        public string image { get; set; }

        public int imageOrder { get; set; }

        public virtual Room_Catalog Room_Catalog { get; set; }
    }
}
