//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Reservation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Reservation_Detail
    {
        [Key]
        [Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int reservationId { get; set; }

        [Key]
        [Column(Order = 1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int roomNumber { get; set; }

        public int numberOfTravelers { get; set; }

        [Display(Name = "Extra Fee")]
        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:#.##}")]
        public decimal extraFee { get; set; }

        [Display(Name = "Total")]
        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:#.##}")]
        public decimal totalPrice { get; set; }

        public virtual Reservation Reservation { get; set; }
        public virtual Room Room { get; set; }
    }
}
