//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Reservation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Reservation_Details = new HashSet<Reservation_Detail>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Display(Name = "Reservation ID")]
        public int reservationId { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "Checkin Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public DateTime checkInDate { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "Checkout Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public DateTime checkOutDate { get; set; }

        [Display(Name = "Customer ID")]
        public int? customerId { get; set; }

        [Required]
        [Display(Name = "Customer Name")]
        [StringLength(50)]
        public string customerName { get; set; }

        [Required]
        [Display(Name = "Phone")]
        [StringLength(50)]
        public string phone { get; set; }

        [Required]
        [Display(Name = "Email")]
        [StringLength(50)]
        public string email { get; set; }

        [Required]
        [Display(Name = "Status")]
        [StringLength(50)]
        public string reservationStatus { get; set; }

        public virtual Registered_Customer Registered_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation_Detail> Reservation_Details { get; set; }
    }
}
